import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.css";
import peaceHand from "../images/peace-hand.svg";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JESSE REAL LIVES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>JESSE REAL LIVES</h1>
      </main>

      <footer className={styles.footer}>
        <span>Powered by </span>
        <Image src={peaceHand} alt="Peace" width={30} height={30} />
        <span>hommus</span>
      </footer>
    </div>
  );
}
